### ISSUE TITLE
Cora, Citeseer, Pubmed三组数据集的结果

### ISSUE THREAD

**Issue by hhhhzzzzz** [BUPT-GAMMA/CPF#5]
您好，
你在论文中写到，你对数据划分，是随机从每个类别选取20个结点，而不是用的GCN中的固定划分，但是paper with code(https://paperswithcode.com/paper/extract-the-knowledge-of-graph-neural)报告你用的固定划分，这点我很疑惑
Following the experimental settings in previous work [23], we
randomly sample 20 nodes from each class as labeled nodes, 30
nodes for validation and all other nodes for test.

**Comment by J-cabin** [comment]
Thank you for your questions. The data division in the original paper is different from the PaperswithCode website. In order to verify the effectiveness furthermore, we have done extra experiments according to the divisions on the paperswithcode website, and have provided the results and hyperparameters in the README.md file.

**Comment by hhhhzzzzz** [comment]
> Thank you for your questions. The data division in the original paper is different from the PaperswithCode website. In order to verify the effectiveness furthermore, we have done extra experiments according to the divisions on the paperswithcode website, and have provided the results and hyperparameters in the README.md file.

非常感谢你及时纠正paperswithcode上面的结果
